server:
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chanwoo.cft3lvedaleb.us-west-2.rds.amazonaws.com:3306/awsDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: chanwoo
    password: a4613112


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug